fix: ensure passwords in helm templates are quoted (#96)
## Description
This is to address issues like the one below when converting yaml to
json:
```
failed to install validator: failed to install validator helm chart: error executing helm upgrade: Release "validator" does not exist. Installing it now.
Error: failed to parse /var/folders/h_/0543c2rd71z0gvw2xbqxcjsr0000gn/T/3171513764: error converting YAML to JSON: yaml: line 69: did not find expected comment or line break
```

The other changes made in the components package to the
`ConfigureXXXPlugin` functions ensure they each setup their structs
correctly to avoid nil pointer dereferences